### ISSUE TITLE
Maksekeskus not updating order status after payment

### ISSUE THREAD

**Issue by rkrindal** [KonektOU/estonian-banklinks-for-woocommerce#14]
I follow all the process and return to merchant. It returns and redirects me to front page because .../wc-api/WC_Banklink_Maksekeskus_Redirect_Gateway/ gives 302 temporarily redirected HTTP status.

Can't say if it is only my issue or not. Is it working perfectly for you guys?

Maksekeskus notification, cancle and return url is .../wc-api/WC_Banklink_Maksekeskus_Redirect_Gateway/  and using POST method.

**Comment by tjuris** [comment]
Good evening!

It works for us in a test environment.

A redirect indicates something redirecting on your side.

Here's a list of what to check:

- do you have the redirect method enabled on Maksekeskus side? We do not support "billing api" yet.
- what is your woocommerce version?
- do you have all woocommerce pages, notably 'order-received', set ( in all languages )?
- have you refreshed permalinks?
- do your other payment methods work, especially any provided by this plugin?
- any errors in debug log ( set DEBUG_LOG to true in wp_config.php )?

There is a redirect after receiving the order, namely to WC_Payment_Gateway->get_return_url(), which is a native WooCommerce method. You might want to verify that it returns a valid url.

It might help to narrow down the issue if you could capture network traffic in browser to see which url is used before the redirect ( in Chrome, "preserve log" under network traffic ),

Please let us know if you make any progress.

**Comment by rkrindal** [comment]
Evening,

Edited some polylang setting and now it does not redirect me from .../wc-api/WC_Banklink_Maksekeskus_Redirect_Gateway/

Instead it gets 404 page not found.

I have refreshed permalinks, got the newest woocommerce version, Maksekeskus side does not offer me  to select which method to use ( there is no such option ).

I'm not using any other payment methods.

What do you mean by do I have order-received set in all languages?

**Comment by tjuris** [comment]
order-received is a WooCommerce endpoint and it does not require any page to be set (sorry, got confused).

Since you're using polylang, is it malfunctioning in all languages?
We haven't tested this plugin with polylang, there might be something specific it requires.
If you can, you could test if disabling polylang makes a difference.

**Comment by alf127** [comment]
Hello,
I am encountering exactly the same problem. After the payment customer is forwarded to the frontpage and no e-mails are sent to customer nor shop administrator. 

Payments work though. 

Im not using multilingual wordpress.

**Comment by RistoNiinemets** [comment]
Hi,

@alf127 the order changing is caused by the reason, that your order was never finished (system error) and cart session is continued.

I have contacted Maksekeskus and found out that they have changed the systems some time ago. Our test user is using older version and all new Maksekeskus customers will be using newer version.

I rewrote the code to the newer system and asked them to update my test user. Newer system should be compatible with older (claimed by them), so it could not cause any issues, but would not be sure on that.

More updates coming soon.

**Comment by alf127** [comment]
Hey,

Thank you for such a prompt answer!

Will be hoping that recent changes made by Maksekeskus are whats causing the problems. I see no other possibility as I know there are many Woocommerce shops using your payment plugin with success.

If you need someone to test that rewritten plugin, then I would be happy to help.

**Comment by RistoNiinemets** [comment]
@alf127 @rkrindal maksekeskus added our test user to the newer system, so I tested it out. latest commit 75d4ff5 should fix the issue. Can one or both of you test the latest code somehow, by downloading it from GitHub?

**Comment by alf127** [comment]
@RistoNiinemets 
Tested and its working perfectly now! Most appreciated!

**Comment by RistoNiinemets** [comment]
@alf127 Thank you! I will release it to the WordPress repository today.

**Comment by rkrindal** [comment]
Mine is still not working and I'm kind of out of ideas..

**Comment by RistoNiinemets** [comment]
@rkrindal POST method is correct. Can you test without Polylang? With WPML and without any translation plugin it works. I think the problem is still with your permalinks or WC API endpoints.

**Comment by alf127** [comment]
Are you sure that you are using correct settings in Maksekeskus Merchant portal?

![maksekeskus_settings](https://cloud.githubusercontent.com/assets/18048434/15314371/127f7d32-1c1a-11e6-8b6f-465dbe9923a0.jpg)

**Comment by rkrindal** [comment]
So I played with polylang setting A LOT and finally got it working with these settings. I will upload an image of my current settings.

Thanks a lot for your time and help @tjuris @alf127 @RistoNiinemets 

<img width="1672" alt="keeled_ _tervisetoode_ _wordpress" src="https://cloud.githubusercontent.com/assets/1631260/15374509/5f16dc32-1d53-11e6-9fc4-2faf313bf38e.png">

**Comment by RistoNiinemets** [comment]
@rkrindal @alf127 Is there any way you could test the current Github version with Maksekeskus API integration? I've tested in on my end, but it needs some more testing before releasing.
