### ISSUE TITLE
Maksekeskus PHP 7.1 workaround and return url patch

### ISSUE THREAD

**Issue by martinl** [KonektOU/estonian-banklinks-for-woocommerce#16]
Hi

here is a patch for Maksekeskus gateway, which:
- fixes Maksekeskus "Failed to create transaction" error message when using PHP 7.1 in a hosting environment. Root cause is json_encode float serialize_precision issue which causes mac calculation to fail (https://stackoverflow.com/questions/42981409/php7-1-json-encode-float-issue). 
- adds return urls (transaction_url) to payment request which simplifies testing and initial setup

I hope you find it useful

[maksekeskus-php7.patch.txt](https://github.com/KonektOU/estonian-banklinks-for-woocommerce/files/1525209/maksekeskus-php7.patch.txt)

**Comment by RistoNiinemets** [comment]
Thanks! That was useful. I solved it a bit differently (766ac810187725ee9883adc85e8180d21dc194d8, 80465ea82768315c83fe7740f5b6e8e76db60c02), as ini_set is not a very clean solution.
